### ISSUE TITLE
"Friends Who Play" doesn't load in library view

### ISSUE THREAD

**Issue by MasterSlenderTR** [TiberiumFusion/FixedSteamFriendsUI#15] opened 2024-05-04 06:46 UTC
As the title says, the "friends who play" tab in library does not load and shows "Sign in".
![1](https://github.com/TiberiumFusion/FixedSteamFriendsUI/assets/50411937/894f4d4f-a1a4-4c15-be76-7b4d37a13068)

However this issue doesn't happen at store page of the game.
![2](https://github.com/TiberiumFusion/FixedSteamFriendsUI/assets/50411937/c75bf99a-3c85-4d0b-818d-a3ad7d69ae90)

This is the version of my Steam client.
![3](https://github.com/TiberiumFusion/FixedSteamFriendsUI/assets/50411937/805706be-63c0-46fe-9ab7-71439fb03d46)

**Comment by TiberiumFusion** [comment] 2024-05-04 21:56
I've never seen that before. Here's what I know about the "friends who play" panel in my testing experience.
- Friends who play works with all patch versions (v1.0.0 to v3.0.1) under the May 2023 steam client. This is my testing baseline for the patch and also the steam client version I personally use daily.
- Friends who play works with all patch versions (v1.0.0 to v3.0.1) under the December 2022 and July 2023 steam clients. I also test against these clients for each patch release.
- Until today, I've only tested patch v1.0.0 against the August 2023 steam client, and I don't remember if friends who play worked in that case. But I just tested the August 2023 client right now, with patch version v3.0.1, and friends who play is working.

Since I'm unable to reproduce this problem in my test environment, we need more information to diagnose the issue.

### Information to collect

#### Console messages from the steam-chat.com snapshot

1. Close Steam, then relaunch it with the following arguments: `-dev -cef-enable-debugging`
  Wait for the library window to load and the Friends List window to appear.
2.  Click somewhere inside the Friends List window and press F12.
  This will cause two windows to open.
3. Find the window titled "DevTools - Steam FriendsUI" and open the Console tab at the top.
4. Scroll through the console messages and take screenshots of the _entire_ list. Post them here.

Tragically, Steam borks the ability to export the console messages to a file. Hence why screenshots are needed instead.


#### Re-test using a clean install of the Steam client

Install a fresh, clean copy of the August 2023 client (no mods, no skins, fully stock). Then install v3.0.1 of the patch and check if friends you play is still broken.
1. Close Steam. Wait for all Steam processes to close!
2. Open `C:\Program Files (x86)` in explorer and find the `Steam` folder.
3. Rename the `Steam` folder to something different, like `Steam.original`.
  This will preserve your existing Steam install, so that you can easily swap back to it.
4. Create a new folder in `C:\Program Files (x86)` named `Steam` that will take the place of the original.
5. Copy `Steam.exe` from your original Steam install into the new empty `Steam` folder.
6. Follow the [forced in-place Steam update instructions](https://github.com/TiberiumFusion/FixedSteamFriendsUI/wiki/Appendix#how-to-perform-a-forced-in-place-steam-update) to install a clean copy of the August 2023 client.
7. Install v3.0.1 of the FixedSteamFriendsUI patch.
8. Launch the newly installed client and check if friends who play is still broken. Post results here.

You can now swap back to your original Steam install like so:
1. Close Steam. Wait for all Steam processes to close!
2. Rename `C:\Program Files (x86)\Steam` to something different, like `Steam.tester`.
3. Rename `C:\Program Files (x86)\Steam.original` back to `Steam`.

#### Operation system information

I'm guessing you're using win32ss's extended kernel on 6.0.6003+, right? This could be related to the issue.

Please post your OS version information and any relevant OS modifications/augmentations that you might be using.

### Explanations

The friends who play panel works by way of some interop between the steam-chat.com webpage and the Steam client. It only works when the friends list is running properly. Beyond that basic info, I have not investigated this communication pathway any further. Thankfully, it just worked as-is while initially developing this patch.

This is completely different from using the Steam client to browse the Steam store website. When you do that, the friends features on the Steam store website (e.g. `123 friends have played this game`) have zero communication with the local data in your Steam client. The Steam store website retrieves the information exclusively from the Valve network. This is why the friends features work if you browse the Steam store website in a normal web browser instead of the Steam client.

<hr/>

And now some totally off-topic things. (which actually I wrote before everything above)

1. Vistaaaaa! :) And holy crap your desktop and taskbar and installed programs and everything is very similar to mine.
2. Your profile picture! Peace through power!
3. I want that skin you have on your Steam client.

It is very cool and very rare to randomly find someone who also still has these interests in 2024.

**Comment by TiberiumFusion** [comment] 2024-07-26 04:35
After discussion with OP, it was revealed that OP was using the old school vgui-based Steam friends/chat in the Steam client, instead of FriendsUI. The vgui version of Steam friends/chat does not work at all with the cef parts of the half cef half vgui clients (afaik), which is why "friends who play" was not working for the OP. Vgui friends simply is not compatible with "friends who play".

It is worth re-iterating here that FixedSteamFriendsUI is only designed to be used with FriendsUI, since that is the problem it targets to fix. FixedSteamFriendsUI is not designed to fix the many issues currently plaguing old school vgui chat. That is out of scope of this project.

However, it is also worth noting that the OP attested to FixedSteamFriendsUI fixing the game streaming/watching feature of the Steam client, when using vgui friends instead of FriendsUI. Evidently, the game streaming feature of FriendsUI is used by the Steam client even when FriendsUI is disabled and vgui friends is enabled instead. OP also noted that FriendsUI-based chat windows appear when using the streaming feature in this scenario, so perhaps FriendsUI is forcibly loaded when the user invokes a game stream/watch, regardless of their vgui vs FriendsUI usage preference.

**Closed** 2024-07-26 04:37 UTC
Labels: Invalid
