### ISSUE TITLE
Download fix?

### ISSUE THREAD

**Issue by DeformedSAS** [TiberiumFusion/FixedSteamFriendsUI#17] opened 2024-11-06 18:36 UTC
will there be a fix for game downloads for older steam clients? because valve broke it somewhere in early 2024 at around march or april

**Comment by TiberiumFusion** [comment] 2024-11-07 00:29
That is completely out of scope of this project.

FixedSteamFriendsUI only changes files within the FriendsUI component of the client. It is completely separate from everything else the client does, including downloads. There is no way FixedSteamFriendsUI can affect the way the client downloads games.

Sorry, really. I also would like to see a fix for that problem.

This has happened to me before. I regularly used the Oct 2 2019 client for several years after its release. When Valve disabled that client's ability to download games, the workaround I used was to install two Steam clients side by side. I added the old client's steamapps to the new client as a library folder. Then I could download games using the newer client, then switch to the old client for daily use to chat and play games. You could try that. You could also use steamcmd to download & update your games the same way (set the games library folder).

> valve broke it somewhere in early 2024 at around march or april

Which client are you using? I recently learned that the Valve disabled the December 2022 client's ability to download games, but that news was last week, not in march or april. Could've been really old news though.

I currently use the May 2023 client daily and it is still capable of downloading games. In fact, afaik everything in that version still works  (friends requires FixedSteamFriendsUI ofc though), so you could switch to that client if needed.

**Comment by DeformedSAS** [comment] 2024-11-07 00:31
aw man. i am using the may 30th 2023 client and i am unable to download anything.. it just fails to start downloads

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TiberiumFusion** [comment] 2024-11-07 00:42
Uh oh. I hope you're not ground zero of an incoming wave of breakage for all May 2023 client users.

I just downloaded a game right now in my May 2023 client to confirm it is working for me. And it is.

Some things to try:
- Restart computer (yeah ik it's dumb, but just in case)
- What is your download region? Try changing it. Open the client settings and go to Downloads -> Download Region. Mine is currently US - Detroit which is how I downloaded that game to test just minutes ago.
- What game are you trying to download? Maybe that specific game has a problem. Try downloading a different game - especially a game that is older than January 2024. Maybe there are some new/updated games using Steam API v21 that fail to download on v20 and older clients (idk).

**Comment by DeformedSAS** [comment] 2024-11-07 00:45
i tried reboot, tried changing download regions from bulgaria to uk spain etc. and i am trying to download an update for war thunder, unturned, gmod x64, cs2 (yes i know cs2 requires api v21 but i have a patch for that so it doesn't matter)

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TiberiumFusion** [comment] 2024-11-07 01:37
Thanks, that's good data. I've been playing a lot of gmod the last few days, and there were no problems downloading updates or addons. Last tested that just a couple hours ago. I stopped playing War Thunder some time ago, but I know it is not a v21 steam api game so it should download fine. Gmod is still v20 btw. So based on those two games, we can say steam api v21 is not the problem, I think.

Also since trying the other download regions didn't fix the problem, that means it's not a broken Steam downloads CDN.

It's possible that the problem is completely separate from Steam and Valve. It could be a problem with your computer's network configuration, your home network, or your internet provider. If you have a VPN, you could try downloading Steam games through the VPN. If the problem is something like censorship, that would fix it.

Otherwise, that's pretty much all I can tell you. I only have a little experience with Steam games downloads failing, so I this is all I know about it. Sorry again.

Try this Steam discussion group: https://steamcommunity.com/groups/ClientDowngrades/discussions/0/
It's from the Steam guide that explains how to install older clients.
You might be able to find someone with the same problem you have, or maybe even a fix.

**Comment by TiberiumFusion** [comment] 2024-11-07 08:06
Closing since this issue is unrelated to FixedSteamFriendsUI, but feel free to continue discussion here anyways.

**Closed by TiberiumFusion** 2024-11-07 08:06 UTC
Labels: Invalid
