### ISSUE TITLE
Steam Client browser ID issue 

### ISSUE THREAD

**Issue by DPoolAGP** [TiberiumFusion/FixedSteamFriendsUI#6] opened 2023-10-13 22:11 UTC
Everytime i open friends and try say clicking on a friend or changing status, it does this before going away again. This is CeceMe from steam, and it doesnt let me hit refresh, I just have to wait until it decides to randomly work. It isnt at a set time, just will randonly work. its been on that screen since last night.
![image](https://github.com/TiberiumFusion/FixedSteamFriendsUI/assets/9343932/9a6ae769-0223-49d5-99b5-42b533fe4112)

**Comment by TiberiumFusion** [comment] 2023-10-14 18:50
Please resize the window and take a new screenshot that shows the entire error message.

Or, launch steam with the `-dev` command line argument, then press F12 to open the blink debug tools, go to the Console tab, and share the contents of the console log.

***

This may be related to issue #5

There is a test version of the patch (intended for issue 5) that might also help with the issue you are experiencing.
If you are interested in trying it, the patch files are here:
[PatchPayload_v1.1.0.1-{00000000-0000-0000-0000-000000000000}.zip](https://github.com/TiberiumFusion/FixedSteamFriendsUI/files/12888847/PatchPayload_v1.1.0.1-.00000000-0000-0000-0000-000000000000.zip)

There's no QuickPatcher this time. You'll have to install the patch manually (see install instructions page on wiki).

And don't worry, you can easily go back to a normal release (like 1.0.0 or 1.1.0) at any time by using the QuickPatcher. It always removes the old patch before installing a new one.

**Comment by DPoolAGP** [comment] 2023-10-17 05:38
![image](https://github.com/TiberiumFusion/FixedSteamFriendsUI/assets/9343932/b81ac92e-98ae-486d-8a6a-11a7de843703)
So This is the version I'm using, which is the one used on the tutorial for "old steam" from this one https://steamcommunity.com/sharedfiles/filedetails/?id=2967855237 and I'll try the patch

**Comment by DPoolAGP** [comment] 2023-10-19 03:57
So even with your patch, I am still getting this issue, even after restarting windows etc

**Comment by TiberiumFusion** [comment] 2023-10-19 19:42
I'm able to reproduce the issue in my test environment with the Dec 2022 steam client. The issue occurs when you invoke the context menu for something, either by right-clicking a friend or by left-clicking the `v` icon near their name.

The problem is that the late July 2023 steam-chat code (which my patch uses as its foundation) tries to use an interface that the Dec 2022 steam client does not create.

Unfortunately, I do not have a circa Dec 2022 snapshot of steam-chat to compare against. So I will take my best guess at appropriately resolving the use of the nonexistent interface in a future update to the patch.

In the meantime, you can avoid the issue by not invoking the context menu.

**Comment by TiberiumFusion** [comment] 2023-10-20 20:49
@DPoolAGP 
A workaround to this issue with `GetBrowserID` (and also another fix to a related Valve screwup re: `IsWindowMaximized`) have been completed and will be in the next release of the patch. It should resolve the issue for you.

I do not have a release date yet for the next version of the patch, but it will be soon™. Until then, you can use [this test version](https://github.com/TiberiumFusion/FixedSteamFriendsUI/files/13058543/PatchPayload_v1.1.0.2-.00000000-0000-0000-0000-000000000000.zip) in the meantime. Follow the manual install steps on the wiki pages to install it.

**Comment by TiberiumFusion** [comment] 2023-10-23 00:11
Patch [version 1.2.0](https://github.com/TiberiumFusion/FixedSteamFriendsUI/releases/tag/Release-v1.2.0) has been released, which resolves this issue.

The specific environment I've tested in is the December 2022 Steam client, but this improvement is also applicable to more older versions that also use `Window.*` methods instead of `Browser.*` methods.

**Closed by TiberiumFusion** 2023-10-23 00:11 UTC
Labels: Patch Files, In Progress
